name: Build and push to ECR.
on: [pull_request]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
         java-version: '21'
         distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

#  push-to-ecr:
#    needs: build-image