name: Build and push to ECR
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  image-build:
    uses: choreography-based-saga/github-actions-templates/.github/workflows/build-image-and-push-to-ecr.yaml@master
    with:
      JAVA_VERSION: "21"
      IMAGE_PATH: "saga-choreography/payment"